;; -*- mode: eask; lexical-binding: t -*-

(package "eglot-jdtls"
         "0.2.0"
         "Eclipse JDT Language Server integration with Eglot")

(website-url "https://github.com/zsxh/eglot-jdtls")
(keywords "eglot" "tools")

(package-file "eglot-jdtls.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "30.1")
(depends-on "compat" "30.1.0.1")
(depends-on "eglot" "1.23")
(depends-on "jsonrpc" "1.0.28")
(depends-on "dape" "0.26.0")
